### ISSUE TITLE
The ss scores of replicating the experiments are different from the ones reported in the stereoset paper

### ISSUE THREAD

**Issue by efatmae** [McGill-NLP/bias-bench#5]
Hi Nicholas,

I used the code in the Github to replicate the intrasentece stereoset scores (ss-score) on the Test set and found differences between my scores and the ones reported in the stereoset paper especially for Bert-base and Roberta-base. Interestingly, the ss-scores for Roberta-large are almost the same. Please look at the attached snapshots for more details. Why do you think there is a difference? 

Best,
Fatma

<img width="997" alt="Screen Shot 2022-06-27 at 3 32 02 PM" src="https://user-images.githubusercontent.com/39276637/176022466-9b4a1149-002d-422b-8e12-ed9301767b9a.png">

<img width="441" alt="Screen Shot 2022-06-27 at 3 34 45 PM" src="https://user-images.githubusercontent.com/39276637/176022481-4ed2b736-5254-4b08-9b97-444539509897.png">

**Comment by ncmeade** [comment]
Hi @efatmae,

Thanks for raising this issue and sorry for the delayed response!

I'll address each of your points separately:

1. **RoBERTa Scores:** The code used to compute the scores for the RoBERTa models in the original StereoSet paper had a bug in it (credit to Matus Pikuliak for finding this). More specifically, the masked tokens for each intrasentence example were encoded *without* a leading whitespace. For instance, if you had the intrasentence example `My little sister is so {annoying,helpful,purse}`, the original  StereoSet code was computing the probabilities for each token without the leading whitespace: `My little sister is so{annoying,helpful,purse}`. This effectively gives you poor performance as the words are non-sensical (e.g., `sopurse`). Thus, the performance of the RoBERTa models in the original StereoSet paper is quite poor (e.g., *roberta-base* has an overall LMS of 71.9% on the test set). This bug only impacted the RoBERTa models as RoBERT's tokenizer treats tokens with and without leading whitespace differently. The bug was present [here](https://github.com/moinnadeem/StereoSet/blob/master/code/dataloader.py#L75) in the original code and was corrected in our [repository](https://github.com/McGill-NLP/bias-bench/blob/main/bias_bench/benchmark/stereoset/dataloader.py#L32).
2. **Results from StereoSet Paper:** Yes, we had issues reproducing the exact results from the original StereoSet paper as well. I've talked with Moin about this before and he suggested that using the exact version of `transformers` (`2.7.0`) from the original paper may help reconcile the differences.

Hopefully this makes sense. Let me know if you have any other questions.

**Comment by efatmae** [comment]
Hi @ncmeade,

Thanks for your reply and for clarifying those points.

Do you mind sharing the scores that you produced for the different models to see if they are similar to the scores I produced or not.

Best,
Fatma

**Comment by ncmeade** [comment]
Sure, I can re-run the code. Was there particular models you were interested in seeing (`bert-base-uncased`, `roberta-base` and `roberta-large`)?

**Comment by efatmae** [comment]
Thanks, @ncmeade, I found all the results I needed in the appendix of the paper. Sorry for keeping the issue open for so long.
